apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: url-shortener
type: Opaque
stringData:
  DB_HOST: url-shortener-db.cjoassqwe7yl.us-east-1.rds.amazonaws.com
  DB_USER: mustafaadmin
  DB_PASS: Mystrongpa$$123db
  DB_NAME: shortener

